### ISSUE TITLE
cognitive_endpoint() seems broken for TextTranslate (Azure Translator)

### ISSUE THREAD

**Issue by quickcoffee** [Azure/AzureCognitive#1]
Hi,
when calling cognitive_endpoint() with either "TextTranslate" or "Translator" I receive an error `Error: Unknown cognitive service`.

Here is the full code:
```
endp <- cognitive_endpoint("https://api.cognitive.microsofttranslator.com/",
                           service_type="TextTranslate", key=cog_translator$list_keys()[1])
```
Also it would be great if the documentation is updated to show the supported cognitive services including the names to be provided to cognitive_endpoint()

**Comment by hongooi73** [comment]
It looks like there have been some changes to endpoint URLs and other low-level details since the package was released. This should hopefully be fixed now.
