### ISSUE TITLE
Subscription is not registered to use namespace

### ISSUE THREAD

**Issue by vikram-rawat** [Azure/AzureCognitive#4]
I want to use speechTotext functionality from azure cognitive services. I would also want to know what service_types are available? But I get an error. Please let me know how to fix it.

```
rg$create_cognitive_service(
   name = "myvisionservice",
   service_type = "speechTotext", 
   service_tier = "S1"
   )
```

```
Error in process_response(res, match.arg(http_status_handler)) : 
  Conflict (HTTP 409). Failed to complete operation. Message:
MissingSubscriptionRegistration
The subscription is not registered to use namespace
'Microsoft.CognitiveServices'. See https://aka.ms/rps-not-found for how to
register subscriptions.
MissingSubscriptionRegistration
Microsoft.CognitiveServices
The subscription is not registered to use namespace
'Microsoft.CognitiveServices'. See https://aka.ms/rps-not-found for how to
register subscriptions.
```
how to resolve this error.

**Comment by vikram-rawat** [comment]
I was able to resolve this issue with this command on powershell azure.

```
Register-AzureRmResourceProvider -ProviderNamespace Microsoft.CognitiveServices
```

But the problem is this framework doesn't have the speech to text API integrated yet and I need it like asap. I am trying to override functions like 

```
get_api_path <- function(type) {
  switch(
    type,
    computervision = "vision/v2.0",
    face = "face/v1.0",
    luis = "luis/v2.0",
    customvision = ,
    customvision_training = ,
    customvision_prediction = "customvision/v3.0",
    contentmoderator = "contentmoderator/moderate/v1.0",
    text = "text/analytics/v2.0",
    cognitiveservices = ,
    texttranslation = "",
    speech2text = "speech/recognition/conversation/cognitiveservices/v1",
    stop("Unknown cognitive service",
         call. = FALSE)
  )
}

```

But it doesn't help a bit. Let me know how can I access this.

**Comment by hongooi73** [comment]
This package isn't a priority for me right now. See [the docs page](https://docs.microsoft.com/en-au/azure/cognitive-services/speech-service/rest-speech-to-text) on the REST APIs for this service; you should be able to extend the code to handle speech to text. In particular, for the [batch API](https://centralus.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/operations/CopyModelToSubscription), you probably want

```
speech2text="speechtotext/v3.0"
```

**Comment by vikram-rawat** [comment]
@hongdai Thanks for replying so quickly... I am trying to debug the code and I am facing a hard time understanding where do I need to make changes, Because I am not familiar with azure or cloud in such I am facing problems.

I could figure out the rest if you could just brief me How should I tackle this issue. I will be able to solve it may be.

Please reply, your few words of guidance could help me a lot at this point.

**Comment by vikram-rawat** [comment]
Hi @hongdai 

I have formatted all the code and added speech to text with a bug fix. But I want to merge the code into github. I don't have the rights to do it.

![image](https://user-images.githubusercontent.com/22342596/113678299-1db05900-96dc-11eb-85c5-895f99d7d67a.png)

Please provide me access to push changes. It will be better for people who need this in future.

**Comment by vikram-rawat** [comment]
As I needed it urgently, I forked the repository and added a 3 functions for speech to text API. And some bugfix... Anybody wish to do the same can open use link link.

https://github.com/vikram-rawat/AzureCognitiveSpeechAPI
