### ISSUE TITLE
Where is the repo for the cognitive search services?

### ISSUE THREAD

**Issue by justinmchase** [Azure/AzureCognitive#6]
The repo associated with this image seems to have disappeared:
https://hub.docker.com/_/microsoft-azure-cognitive-services

Do you happen to know where the new location is?

**Comment by justinmchase** [comment]
@hongooi73 @microsoftopensource Any updates on this?

**Comment by hongooi73** [comment]
Hi, this repo is purely for the R package, which is a standalone project and independent of the Cognitive Services team. I'm actually no longer with MS, so I don't know who would be the best contact, sorry.

That said, the URL is up for me, so maybe try it again.

**Comment by justinmchase** [comment]
They're all public archives, can't seem to find the real codebase anymore. Well anyway, thanks.
